name       : i3status
version    : '2.13'
release    : 9
source     :
    - https://i3wm.org/i3status/i3status-2.13.tar.bz2 : ce89c9ff8565f62e88299f1a611229afdfc356b4e97368a5f8c4f06ad2fa1466
license    : MIT
component  : desktop.i3
summary    : i3status is a small program for generating a status bar for i3bar, dzen2, xmobar or similar programs.
description: |
    i3status is a small program for generating a status bar for i3bar, dzen2, xmobar or similar programs.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(yajl)
    - asciidoc
    - xmlto
setup      : |
    %configure
build      : |
    %make -C x86_64-solus-linux-gnu
install    : |
    %make_install -C x86_64-solus-linux-gnu
    install -Dm00644 $pkgfiles/i3status.conf $installdir/etc/i3status.conf
