name       : i3status
version    : '2.14'
release    : 14
source     :
    - https://i3wm.org/i3status/i3status-2.14.tar.xz : 5c4d0273410f9fa3301fd32065deda32e9617fcae8b3cb34793061bf21644924
license    : MIT
component  : desktop.i3
summary    : i3status is a small program for generating a status bar for i3bar, dzen2, xmobar or similar programs.
description: |
    i3status is a small program for generating a status bar for i3bar, dzen2, xmobar or similar programs.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(yajl)
    - asciidoc
    - xmlto
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/i3status.conf $installdir/etc/i3status.conf
