name       : i3status
version    : '2.11'
release    : 8
source     :
    - https://i3wm.org/i3status/i3status-2.11.tar.bz2 : 98db7e730f0ce908eb656ac10d713ae6a885676621391d54f00b719752f18c5f
license    : MIT
component  : desktop.i3
summary    : i3status is a small program for generating a status bar for i3bar, dzen2,
    xmobar or similar programs.
description: |
    i3status is a small program for generating a status bar for i3bar, dzen2, xmobar or similar programs.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libconfuse)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-render)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(yajl)
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/i3status.conf $installdir/etc/i3status.conf
